### PR TITLE
Add P125M switch support

### PR DESCRIPTION
**Pull request by irubnich**
Looks like it just needed an entry in `const.py`!

### CODE REVIEW

**Review by wash3re — COMMENTED** [review]
I tried it, it did not work.  It still doesn't show the load.

**Comment by irubnich** [comment]
> I tried it, it did not work. It still doesn't show the load.

This just added support for core switching functionality, not load. I couldn't get that working either.

**Comment by wash3re** [comment]
By load I mean switch control.  (Switching of the load).  I only see two items overload and wifi signal.

**Comment by irubnich** [comment]
> By load I mean switch control. (Switching of the load). I only see two items overload and wifi signal.

Oh I see. That may have to do with how you load custom components. To get this working for me I had to manually edit the file. I didn't touch the repo or anything. And then I restarted the server. I'm unsure how to do this more legitimately and it's  probably different across setups (docker, hass OS, etc).

**Comment by wash3re** [comment]
Yep, that fixed it.

**Review by wash3re — APPROVED** [review]

**Review by wash3re — APPROVED** [review]

**Comment by cfurini** [comment]
> > By load I mean switch control. (Switching of the load). I only see two items overload and wifi signal.
> 
> Oh I see. That may have to do with how you load custom components. To get this working for me I had to manually edit the file. I didn't touch the repo or anything. And then I restarted the server. I'm unsure how to do this more legitimately and it's probably different across setups (docker, hass OS, etc).

I'm running with the same issue. What file more specifically you had to edit to make it work?

**Pull request merged**
