### PR TITLE
Add KE100 Support

### PR DESCRIPTION
**Pull request by delatt**
Add KE100 Support for:

- Climate control (Heat and off)
- Frost Protection
- Temperature Offset
- Child Lock
- Battery Sensor
- Temperature

Features like night  and sleep mode will need to be looked into further, they're not easily exposed.

I've written unit tests for what I can but we'll need to figure out some form of integration testing for the harder bits.

@petretiandrea

### CODE REVIEW

**Comment by delatt** [comment]
@petretiandrea Hope everything looks okay :)

**Comment by petretiandrea** [comment]
Thanks for your support, I will merge it asap

**Comment by mc-flash** [comment]
Hi together,
I'm totally new to HA and Github and now purchased the KE100 thermostats (had Somfy io and Bosch but both disappointed me).
Do I understand right that soon the thermostats will be fully compatible with HA?

**Comment by MaxDusdal** [comment]
> Hi together, I'm totally new to HA and Github and now purchased the KE100 thermostats (had Somfy io and Bosch but both disappointed me). Do I understand right that soon the thermostats will be fully compatible with HA?

Have also ordered them a few days ago since I really like the Tapo ecosystem and they were on sale, would be great to get an ETA

**Comment by delatt** [comment]
> Hi together, I'm totally new to HA and Github and now purchased the KE100 thermostats (had Somfy io and Bosch but both disappointed me). Do I understand right that soon the thermostats will be fully compatible with HA?

You'll have functionality to import them and use the functionality stated in the PR description. The other functionality might be added at some point.

**Comment by mc-flash** [comment]
Thanks for your work, that's great!
Most important for me is to see the actual temperature (already working perfect with the temperature and humidity sensor).

Stuff like child lock and night mode is not so important for me to see in HA.
We still need to use the Kasa App for the time schedule, right? I activate child lock there and everything's okay.

What do you think, when will it be usable?

**Comment by delatt** [comment]
Yes you will need the App for schedules, if there's enough appetite I'll
see if I can figure something out.

The code should be ready to go,  just need petretiandrea to run some checks
and merge.

**Comment by Redgewell** [comment]
This is fabulous , thanks to you @delatt and @petretiandrea, I can now see my TP-Link radiator TRV’s in Home assistant. (See bottom 4 in pic.)

@delatt do you have a “buy me a coffee” link? 

IMG_5183

**Comment by delatt** [comment]
That's great to see, let me know if there are any issues :)

I do have one now, there's no need but thank you!

https://www.buymeacoffee.com/thaeryn

**Comment by mc-flash** [comment]
Screenshot_2023-11-26-18-35-35-257_io homeassistant companion android

Can anyone help me?!
Still I only have the device without entities in HA (like the last days since I own the KE100).

Restarted HA, re installed Tapo Controller, waited a few hours... Nothing helped

**Comment by delatt** [comment]
Well I don't think @petretiandrea has released a new version, I'm guessing @Redgewell used some manual method to get the update

**Comment by mc-flash** [comment]
Thanks for the quick reply.
Then I'll need to wait for the new version. Manual coding is not really my favorite hobby ;)

**Comment by mc-flash** [comment]
@Redgewell 
Thank you very much, that was the solution!

I can now even control half degrees, which is not possible in the Kasa App. 

I thought that the Main version is the oldest one. That's why I didn't try that one. 
Good to know for the future

**Comment by MaxDusdal** [comment]
I'm having this issue where the child lock is active in homeassistant and even in the Kasa app but the TRV itself doesn't really lock and changes are still possible by rotsating the dial. Does anyone here have any information on why that happens?

**Comment by leed71** [comment]
This is awesome news and for those in the UK they're 30 quid a pair in the black friday sales

**Comment by petretiandrea** [comment]
Now is officially avaiable on v2.12.0

**Comment by Redgewell** [comment]
> Now is officially avaiable on v2.12.0

confirmed, installed and working ~ thanks.

**Comment by delatt** [comment]
That's great to hear!

**Comment by MaxDusdal** [comment]
> That's strange, I'm seeing that behaviour too. I must admit I didn't check the child lock on the TRV when testing, I assumed if it went through to the app it would get to the TRV. I've compared the device state that we have available when toggled via HA and the app but I can't see a difference. I'm tempted to say this is something on TP-Link's side but I can try digging further at some point.
> 
> I am curious how your TRVs are being picked up from main? mine isn't so I had to use my development environment. It also looks like there might be a bug on main, @petretiandrea has a PR open to fix this.
@delatt 

I had this extension installed prior to the update for the KE100 and they were always detected but just didn't have any entities. When I got a notification that the PR has been merged I have just updated to the main branch because I had whatever release was first in list installed and from there on my TRV's have been picked up immeaditely and been ready to go. I just tested the Child Locks. When enabling from the app the child lock gets triggered. But when enabling from HomeKit or Homeassistant for that matter the state in the app changes, but the TRV themselves do not acknowledge the change in state. I would love to somehow support this project, it's just that I have no clue how home assistant or kasa works.

**Comment by raiback25** [comment]
hello, I'm new here. What is the exact procedure to get the KH100 into the home assistant?

**Comment by petretiandrea** [comment]
Install the integration on HA following README.md and then add your device from home assistant by using the KE100 ip (you can find in tapo app)

**Comment by whatamanoffical** [comment]
@petretiandrea I hop you can help me!

1) I had a working integration with 8 KE100 thermostats in HA. I use TAPO Hub and KASA hub at home on dynamic IPs, everything is integrated in the **TAPO app** and worked before I had to restart my router (due to another reason). Now, after the restart of the router, the integration stopped working for the KE100 via TAPO. I tried to remove, change IP adress etc. I decided to give the KASA and TAPO Hub static ips now but I do reach the host when adding into the integration and get the notorious failed to connect error: 

Screenshot 2024-01-31 at 11 09 15


Questions: 

1) Should I connect as HOST to the Ip adress of the a) KASA HUB or the b) TAPO HUB (both integrated in TAPO app)
2) Do you recommend static or dynamic IP? 

**Any comments or hints would be highly appreciated!!! Thank you** 

Here comes my logs: 

```
2024-01-31 11:07:39.775 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.052 seconds (success: True)
2024-01-31 11:08:09.768 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.045 seconds (success: True)
2024-01-31 11:08:39.776 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.053 seconds (success: True)
2024-01-31 11:09:09.767 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.043 seconds (success: True)
2024-01-31 11:09:39.782 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.058 seconds (success: True)
2024-01-31 11:09:48.648 ERROR (MainThread) [custom_components.tapo.config_flow] Failed to setup cannot connect 
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 992, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1085, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1069, in create_connection
    sock = await self._connect_sock(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 973, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 628, in sock_connect
    return await fut
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 668, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
TimeoutError: [Errno 110] Connect call failed ('192.168.68.103', 80)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/tapo/config_flow.py", line 192, in _get_first_data_from_api
    (await tapo_client.get_device_info())
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/api/tapo_client.py", line 92, in get_device_info
    return await self.execute_raw_request(get_info_request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/api/tapo_client.py", line 77, in execute_raw_request
    await self._initialize_protocol_if_needed()
  File "/usr/local/lib/python3.11/site-packages/plugp100/api/tapo_client.py", line 71, in _initialize_protocol_if_needed
    await self._guess_protocol()
  File "/usr/local/lib/python3.11/site-packages/plugp100/api/tapo_client.py", line 221, in _guess_protocol
    response = await self.get_component_negotiation()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/api/tapo_client.py", line 81, in get_component_negotiation
    return (await self.execute_raw_request(TapoRequest.component_negotiation())).map(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/api/tapo_client.py", line 78, in execute_raw_request
    return (await self._protocol.send_request(request)).map(lambda x: x.result)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/protocol/passthrough_protocol.py", line 41, in send_request
    response = await self._send_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/protocol/passthrough_protocol.py", line 61, in _send_request
    await self._login_with_version(self._credential)
  File "/usr/local/lib/python3.11/site-packages/plugp100/protocol/passthrough_protocol.py", line 80, in _login_with_version
    session_or_error = await self._passthrough.handshake(self._url)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/protocol/securepassthrough_transport.py", line 70, in handshake
    response = await self._http.async_make_post(url, json=request_body)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/common/utils/http_client.py", line 18, in async_make_post
    async with self.session.post(
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 1187, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 574, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 911, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 1235, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 1204, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 1000, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 192.168.68.103:80 ssl:default [Connect call failed ('192.168.68.103', 80)]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/tapo/config_flow.py", line 119, in async_step_user
    device_data = await self._get_first_data_from_api(tapo_client)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tapo/config_flow.py", line 199, in _get_first_data_from_api
    raise CannotConnect from error
custom_components.tapo.errors.CannotConnect

```

**Comment by Bavariusthefirst** [comment]
Hi @delatt, im struggling a little bit to get the KE100 on HA. I managed to find my KH100 bridge as well as the P100 sockets. 

I noticed that Tapo app no longer supports the KE100, which means that I can’t merge my Kasa and Tapo account. Any other idea what I could do to get them on HA? 

Thanks for you efforts!

**Comment by delatt** [comment]
Hi @Bavariusthefirst , apologies but I've not been following much with HA for a couple of months now, so I'm not up to date with what's happening. Perhaps @petretiandrea can shed some light?

**Comment by whatamanoffical** [comment]
I think a good workaround is to add the kasas hub ip in tapo integration. That works for me. Sent from my iPhoneOn 14 Apr 2024, at 16:59, Del ***@***.***> wrote:﻿
Hi @Bavariusthefirst , apologies but I've not been following much with HA for a couple of months now, so I'm not up to date with what's happening. Perhaps @petretiandrea can shed some light?

**Pull request merged**
